dist: trusty
sudo: false
group: beta
language: c
os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nim ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://http.us.debian.org/debian/pool/main/n/nim/nim_0.16.0-1_amd64.deb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://http.us.debian.org/debian/pool/main/o/openssl1.0/libssl1.0.2_1.0.2k-1_amd64.deb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i *_amd64.deb ; fi

script:
  - nimble install zip -y
  - nim c -p:. tests/test_morelogging.nim
  - nim c -p:. tests/test_threaded.nim
  - nim c -p:. tests/test_threaded_performance.nim
  - ./tests/test_morelogging
  - ./tests/test_threaded
  - ./tests/test_threaded_performance

branches:
  except:
    - gh-pages
