version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim
    steps:
      - run: echo 'export PATH=~/.nimble/bin:$PATH' >> $BASH_ENV
      - checkout
      # Reuse cached Nim compiler
      - restore_cache:
          key: cache-0001
      - run:
          command: |
            nimble install zip -y
      - save_cache:
          key: cache-0001
          paths:
            - ~/.nimble
            - ~/.choosenim
      - run:
          command: |
            nim c -p:. -r tests/test_morelogging.nim
            #LD_LIBRARY_PATH=/usr/local/lib ./test_sodium
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
