version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim
    steps:
      - checkout
      - run:
          command: |
            nimble install zip -y
            wget https://ooni-data.s3.amazonaws.com/autoclaved/jsonl.tar.lz4/2019-07-20/20190720T013740Z-AR-AS16814-web_connectivity-20190720T013741Z_AS16814_MW5maiQ4Y79mep6uKi9mu0TGM7RreZ2SKs9ep0hZ5IOdrfXh7f-0.2.0-probe.json.lz4 -O j.lz4
            apt-get install -y liblz4-tool python-ujson
            time lz4cat j.lz4 > j
            echo bench python
            python -m timeit -s "import ujson;j=open('j').readlines()" "[len(ujson.loads(l)) for l in j]"
            echo bench NIm
            nim c -d:danger --hints:off -r t.nim
            ./t
            ./t
            ./t
            ./t

